local base = GameData.status_base.base

table.insert(base, {
	["status_name"] = "DIED",
	["id"] = 1,
	["unique"] = true,
	["immunity"] = {"IDLE", "MOVE", "CAST", "STATUS_CAST"},
	["mutex"] = {"FULL_ENERGY", "FROST", "CORROSION_VENOM", "CAST", "STATUS_CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 2,
	["desc"] = "死亡",
	})
table.insert(base, {
	["status_name"] = "MOVE",
	["id"] = 2,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["mutex"] = {"IDLE"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "移动",
	})
table.insert(base, {
	["status_name"] = "IDLE",
	["id"] = 3,
	["cancel_formula"] = true,
	["end_formula"] = true,
	["unique"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "空闲",
	})
table.insert(base, {
	["status_name"] = "CAST",
	["id"] = 4,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["immunity"] = {"IDLE"},
	["cover"] = true,
	["mutex"] = {"IDLE", "MOVE"},
	["can_move"] = false,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "施法中",
	})
table.insert(base, {
	["status_name"] = "CAST_WARNING",
	["id"] = 5,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cancel_formula"] = true,
	["end_formula"] = true,
	["unique"] = true,
	["immunity"] = {"IDLE", "CAST"},
	["cover"] = true,
	["mutex"] = {"IDLE", "MOVE", "CAST"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 2,
	["desc"] = "施法警告",
	})
table.insert(base, {
	["status_name"] = "STATUS_CAST",
	["id"] = 6,
	["apply_formula"] = true,
	["update_formula"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "并行状态施法",
	})
table.insert(base, {
	["status_name"] = "FULL_ENERGY",
	["id"] = 7,
	["unique"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "充能满",
	})
table.insert(base, {
	["status_name"] = "FORCE_IDLE",
	["id"] = 8,
	["apply_formula"] = true,
	["update_formula"] = true,
	["immunity"] = {"IDLE"},
	["cover"] = true,
	["mutex"] = {"IDLE"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "强制空闲",
	})
table.insert(base, {
	["status_name"] = "IN_AIR",
	["id"] = 10,
	["apply_formula"] = true,
	["unique"] = true,
	["mutex"] = {"ON_GROUND"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "在空中",
	})
table.insert(base, {
	["status_name"] = "ON_GROUND",
	["id"] = 11,
	["apply_formula"] = true,
	["unique"] = true,
	["mutex"] = {"IN_AIR"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "在地面",
	})
table.insert(base, {
	["status_name"] = "STATIC",
	["id"] = 12,
	["unique"] = true,
	["immunity"] = {"MOVE"},
	["can_move"] = false,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "不可移动",
	})
table.insert(base, {
	["status_name"] = "PUSHED",
	["id"] = 13,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cancel_formula"] = true,
	["immunity"] = {"MOVE"},
	["cover"] = true,
	["mutex"] = {"IDLE", "MOVE"},
	["can_move"] = false,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "被推动中",
	})
table.insert(base, {
	["status_name"] = "FLOATED",
	["id"] = 14,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 2,
	["desc"] = "受击浮空",
	})
table.insert(base, {
	["status_name"] = "HURTLESS",
	["id"] = 15,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "无敌",
	})
table.insert(base, {
	["status_name"] = "EXPOSE_ARMOR",
	["id"] = 100,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "破甲",
	})
table.insert(base, {
	["status_name"] = "FROST",
	["id"] = 101,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 3,
	["desc"] = "冰冻",
	})
table.insert(base, {
	["status_name"] = "POISONING",
	["id"] = 102,
	["apply_formula"] = true,
	["update_formula"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "剧毒",
	})
table.insert(base, {
	["status_name"] = "BLINDNESS",
	["id"] = 103,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "致盲",
	})
table.insert(base, {
	["status_name"] = "DOPING",
	["id"] = 104,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "兴奋剂",
	})
table.insert(base, {
	["status_name"] = "ATTACK_REDUCED",
	["id"] = 105,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "减攻",
	})
table.insert(base, {
	["status_name"] = "CAPTIVITY",
	["id"] = 106,
	["apply_formula"] = true,
	["update_formula"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 3,
	["desc"] = "囚禁",
	})
table.insert(base, {
	["status_name"] = "LOCKED",
	["id"] = 107,
	["apply_formula"] = true,
	["update_formula"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 3,
	["desc"] = "锁定",
	})
table.insert(base, {
	["status_name"] = "DIZZINESS",
	["id"] = 108,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 3,
	["desc"] = "眩晕",
	})
table.insert(base, {
	["status_name"] = "CORROSION_VENOM",
	["id"] = 109,
	["apply_formula"] = true,
	["update_formula"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "剧毒腐蚀",
	})
table.insert(base, {
	["status_name"] = "VENOM_CURE",
	["id"] = 110,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "腐蚀回复",
	})
table.insert(base, {
	["status_name"] = "FRENZY",
	["id"] = 111,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "狂暴",
	})
table.insert(base, {
	["status_name"] = "VIRUS",
	["id"] = 112,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "病毒",
	})
table.insert(base, {
	["status_name"] = "SUPER_VIRUS",
	["id"] = 113,
	["apply_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "超级病毒",
	})
table.insert(base, {
	["status_name"] = "ATTACK_DISABLE",
	["id"] = 114,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["mutex"] = {"CAST", "CAST_WARNING"},
	["can_move"] = true,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 3,
	["desc"] = "禁止攻击",
	})
table.insert(base, {
	["status_name"] = "AS_DOWN",
	["id"] = 115,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "攻击减速",
	})
table.insert(base, {
	["status_name"] = "INCREASE_ARMOR",
	["id"] = 116,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "护甲提升",
	})
table.insert(base, {
	["status_name"] = "GRAVITY_FIELD",
	["id"] = 117,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "重力力场",
	})
table.insert(base, {
	["status_name"] = "SLEEPING",
	["id"] = 118,
	["apply_formula"] = true,
	["update_formula"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 2,
	["desc"] = "睡眠中",
	})
table.insert(base, {
	["status_name"] = "TEMP_SHIELD",
	["id"] = 119,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "单体护罩",
	})
table.insert(base, {
	["status_name"] = "A_ALL_ATTACK",
	["id"] = 120,
	["apply_formula"] = true,
	["end_formula"] = true,
	["mutex"] = {"A_ALL_DEFANCE"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "全攻光环",
	})
table.insert(base, {
	["status_name"] = "ALL_ATTACK",
	["id"] = 121,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["mutex"] = {"ALL_DEFANCE"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "全攻",
	})
table.insert(base, {
	["status_name"] = "A_ALL_DEFANCE",
	["id"] = 122,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["mutex"] = {"A_ALL_ATTACK"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "全守光环",
	})
table.insert(base, {
	["status_name"] = "ALL_DEFANCE",
	["id"] = 123,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["mutex"] = {"ALL_ATTACK"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "全守",
	})
table.insert(base, {
	["status_name"] = "ULTIMATE_FORM",
	["id"] = 124,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "终极形态",
	})
table.insert(base, {
	["status_name"] = "TENZAI_SKILL_04",
	["id"] = 125,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "Tenzai04",
	})
table.insert(base, {
	["status_name"] = "DEFEND_FIELD",
	["id"] = 126,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "防护力场",
	})
table.insert(base, {
	["status_name"] = "ALLOY_ARMOR",
	["id"] = 127,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "超合金装甲",
	})
table.insert(base, {
	["status_name"] = "TAKEZO_SKILL_01",
	["id"] = 128,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "弹一闪",
	})
table.insert(base, {
	["status_name"] = "BATTLE_FRENZY",
	["id"] = 129,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 2,
	["desc"] = "战斗狂热",
	})
table.insert(base, {
	["status_name"] = "BLADE_MASTER",
	["id"] = 130,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "奥义·剑舞者",
	})
table.insert(base, {
	["status_name"] = "PHYSICAL_ANOMALY",
	["id"] = 131,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "反物理装甲",
	})
table.insert(base, {
	["status_name"] = "BLOCK_STYLE",
	["id"] = 132,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "格挡姿势",
	})
table.insert(base, {
	["status_name"] = "BLOOD_VARIATION",
	["id"] = 133,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "变异血统",
	})
table.insert(base, {
	["status_name"] = "PREDICT_ATTACK",
	["id"] = 134,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "预判攻击",
	})
table.insert(base, {
	["status_name"] = "FORCE_FAVORED",
	["id"] = 135,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "原力眷顾",
	})
table.insert(base, {
	["status_name"] = "FIRE_ICE_SKILL",
	["id"] = 136,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "冰火特技",
	})
table.insert(base, {
	["status_name"] = "ICE_COLD",
	["id"] = 137,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "冰冷减速",
	})
table.insert(base, {
	["status_name"] = "ARMOR_PENETRATION",
	["id"] = 138,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "穿甲",
	})
table.insert(base, {
	["status_name"] = "BLAST_SHELL",
	["id"] = 139,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "薄弱洞悉",
	})
table.insert(base, {
	["status_name"] = "CUTIN_ARMOR",
	["id"] = 140,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "角质装甲",
	})
table.insert(base, {
	["status_name"] = "STAGNATION",
	["id"] = 141,
	["apply_formula"] = true,
	["update_formula"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["type"] = 3,
	["desc"] = "停滞",
	})
table.insert(base, {
	["status_name"] = "ENHANCED_SHIELD",
	["id"] = 142,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "加强型护盾",
	})
table.insert(base, {
	["status_name"] = "INSPIRE",
	["id"] = 143,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "鼓舞",
	})
table.insert(base, {
	["status_name"] = "UNYIELDING",
	["id"] = 144,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "执着",
	})
table.insert(base, {
	["status_name"] = "SWARM_EFFECT",
	["id"] = 145,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "蜂群效应",
	})
table.insert(base, {
	["status_name"] = "ENERGY_REPLACEMENT",
	["id"] = 146,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "能量置换",
	})
table.insert(base, {
	["status_name"] = "REPAIR_SHIELD",
	["id"] = 147,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "护盾修补",
	})
table.insert(base, {
	["status_name"] = "MECHA_DEFANCE",
	["id"] = 148,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "全能机甲",
	})
table.insert(base, {
	["status_name"] = "SHARP_TEETH",
	["id"] = 149,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "锋锐之牙",
	})
table.insert(base, {
	["status_name"] = "TOUCH_VIRUS",
	["id"] = 150,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "病毒之触",
	})
table.insert(base, {
	["status_name"] = "WEAKEN_VIRUS",
	["id"] = 151,
	["apply_formula"] = true,
	["end_formula"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "虚弱病毒",
	})
table.insert(base, {
	["status_name"] = "INTERCEPT_REAGENT",
	["id"] = 152,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "格挡药剂",
	})
table.insert(base, {
	["status_name"] = "ATTACK_REAGENT",
	["id"] = 153,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "攻击药剂",
	})
table.insert(base, {
	["status_name"] = "DOPING_MAX_HP",
	["id"] = 154,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "HP兴奋剂",
	})
table.insert(base, {
	["status_name"] = "METEORITE_IMPACT",
	["id"] = 155,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "陨石撞击",
	})
table.insert(base, {
	["status_name"] = "FIRE_CAGE",
	["id"] = 156,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["mutex"] = {"CAST", "CAST_WARNING", "MOVE"},
	["can_move"] = false,
	["can_attack"] = false,
	["can_cast"] = false,
	["desc"] = "火焰囚笼",
	})
table.insert(base, {
	["status_name"] = "DEVOUT",
	["id"] = 157,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "虔诚",
	})
table.insert(base, {
	["status_name"] = "ELI_SKILL_1",
	["id"] = 158,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "Eli 光明祭礼·米迦勒",
	})
table.insert(base, {
	["status_name"] = "ELI_SKILL_2",
	["id"] = 159,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "Eli 光明祭礼·拉斐尔",
	})
table.insert(base, {
	["status_name"] = "ELI_SKILL_3",
	["id"] = 160,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "Eli 光明祭礼·加百列",
	})
table.insert(base, {
	["status_name"] = "DEFENDER",
	["id"] = 161,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "加百列守护者",
	})
table.insert(base, {
	["status_name"] = "CHAOS",
	["id"] = 162,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "混乱",
	})
table.insert(base, {
	["status_name"] = "DOUBLE_FIRE",
	["id"] = 163,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "连发狙枪",
	})
table.insert(base, {
	["status_name"] = "NO_DISTRACTION",
	["id"] = 164,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "心无旁骛",
	})
table.insert(base, {
	["status_name"] = "BURST_GRENADE",
	["id"] = 165,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "高爆榴弹",
	})
table.insert(base, {
	["status_name"] = "INSTABILITY_GRENADE",
	["id"] = 166,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "不稳定榴弹",
	})
table.insert(base, {
	["status_name"] = "SKILL_SEAL",
	["id"] = 167,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["mutex"] = {"CAST", "CAST_WARNING"},
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = false,
	["desc"] = "沉默技能释放",
	})
table.insert(base, {
	["status_name"] = "TAKEZO_REVERT",
	["id"] = 168,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "奥义·回复",
	})
table.insert(base, {
	["status_name"] = "BLOOD_SIGNAL",
	["id"] = 169,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "血之印记",
	})
table.insert(base, {
	["status_name"] = "BLOOD_SOUL",
	["id"] = 170,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "血魂",
	})
table.insert(base, {
	["status_name"] = "TANK_FIXED",
	["id"] = 171,
	["cover"] = true,
	["can_move"] = false,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "坦克架起",
	})
table.insert(base, {
	["status_name"] = "ARES_03",
	["id"] = 172,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "天启装甲",
	})
table.insert(base, {
	["status_name"] = "ARES_04",
	["id"] = 173,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "自由星燕",
	})
table.insert(base, {
	["status_name"] = "DEATH_RAID",
	["id"] = 174,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "绝命突袭",
	})
table.insert(base, {
	["status_name"] = "OVERLOAD_ORDER",
	["id"] = 175,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "过载指令",
	})
table.insert(base, {
	["status_name"] = "DEFANCE_ORDER",
	["id"] = 176,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "防御指令",
	})
table.insert(base, {
	["status_name"] = "CORROSION_STYLE",
	["id"] = 177,
	["apply_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "腐蚀风格攻击",
	})
table.insert(base, {
	["status_name"] = "CORROSION",
	["id"] = 178,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "腐蚀性",
	})
table.insert(base, {
	["status_name"] = "TECH_DEFENCE",
	["id"] = 179,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "科技护盾",
	})
table.insert(base, {
	["status_name"] = "TECH_DEFENCE_ATK",
	["id"] = 180,
	["apply_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "科技护盾攻击",
	})
table.insert(base, {
	["status_name"] = "ELECTRO_PULSE",
	["id"] = 181,
	["apply_formula"] = true,
	["update_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "电磁脉冲",
	})
table.insert(base, {
	["status_name"] = "TECH_DEFENCE_MASTER",
	["id"] = 182,
	["apply_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "护盾精研",
	})
table.insert(base, {
	["status_name"] = "CONFUSION",
	["id"] = 183,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 3,
	["desc"] = "魅惑",
	})
table.insert(base, {
	["status_name"] = "CONFUSION_IMMUNE",
	["id"] = 184,
	["immunity"] = {"CONFUSION"},
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["type"] = 1,
	["desc"] = "心灵强化",
	})
table.insert(base, {
	["status_name"] = "DESPERATE_ATTACK",
	["id"] = 185,
	["apply_formula"] = true,
	["unique"] = true,
	["cover"] = false,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "亡命攻击",
	})
table.insert(base, {
	["status_name"] = "IRRITABLE",
	["id"] = 186,
	["apply_formula"] = true,
	["update_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "急躁",
	})
table.insert(base, {
	["status_name"] = "SOUL_BARRIER",
	["id"] = 187,
	["apply_formula"] = true,
	["end_formula"] = true,
	["cover"] = true,
	["can_move"] = true,
	["can_attack"] = true,
	["can_cast"] = true,
	["desc"] = "灵魂壁垒",
	})
